import { appRoutes } from "@/lib/routes";
import type { ProductTourStep } from "@/modules/product-tour/product-tour-types";

export const PRODUCT_TOUR_STEPS: ProductTourStep[] = [
  {
    id: "dashboard_summary",
    route: appRoutes.dashboard,
    target: "dashboard-summary",
    title: "Resumo financeiro",
    description: "Este bloco resume saldo, entradas e saidas logo na chegada ao dashboard.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "dashboard_transactions",
    route: appRoutes.dashboard,
    target: "dashboard-transactions",
    title: "Transações recentes",
    description: "Aqui você valida rapidamente as últimas movimentações sem sair da tela inicial.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "dashboard_insights",
    route: appRoutes.dashboard,
    target: "dashboard-insights",
    title: "Insights do dashboard",
    description: "Os insights apontam padroes, desvios e oportunidades de ajuste com base nos seus dados.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "dashboard_accounts",
    route: appRoutes.dashboard,
    target: "dashboard-banks",
    title: "Contas conectadas",
    description: "Esta área mostra suas contas, cartões e saldo por origem para facilitar a leitura do caixa.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "accounts_summary",
    route: appRoutes.accounts,
    target: "accounts-summary",
    title: "Resumo de contas",
    description: "Os cards iniciais mostram rapidamente quantas contas bancárias, cartões e caixas você tem.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "accounts_structure",
    route: appRoutes.accounts,
    target: "accounts-structure",
    title: "Estrutura financeira",
    description: "Aqui você organiza contas, revisa cartões vinculados e acompanha a hierarquia da sua estrutura.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "accounts_support",
    route: appRoutes.accounts,
    target: "accounts-support",
    title: "Painel lateral",
    description: "Este card lateral complementa a leitura da página e pode receber orientações e próximas ações.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "transactions_filters",
    route: appRoutes.transactions,
    target: "transactions-filters",
    title: "Filtros de transações",
    description: "Use estes filtros para recortar período, categoria, busca e tipo antes de analisar os dados.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "transactions_summary",
    route: appRoutes.transactions,
    target: "transactions-summary",
    title: "Resumo filtrado",
    description: "Os cards resumem receitas, despesas e saldo considerando somente o recorte atual.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "transactions_table",
    route: appRoutes.transactions,
    target: "transactions-table",
    title: "Tabela de transações",
    description: "Aqui você revisa cada lançamento, importa arquivos e cria novas movimentações.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "transactions_categories",
    route: appRoutes.transactions,
    target: "transactions-categories",
    title: "Categorias",
    description: "Este painel ajuda a entender o peso de cada categoria e ajustar a classificação rapidamente.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "recurring_income_filters",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-filters",
    title: "Filtros de receitas recorrentes",
    description: "Comece por aqui para definir período, conta e categoria das entradas previsíveis.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "recurring_income_summary",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-summary",
    title: "Resumo das recorrencias",
    description: "Os cards mostram volume, séries ativas, média e próximas ocorrências das receitas recorrentes.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "recurring_income_chart",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-chart",
    title: "Analise visual",
    description: "Este bloco combina gráfico e distribuição para revelar onde as receitas recorrentes se concentram.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "recurring_income_table",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-table",
    title: "Tabela de recorrencias",
    description: "A tabela detalha cada série e permite editar ou remover ocorrências do período.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "installments_summary",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-summary",
    title: "Resumo de parcelamentos",
    description: "Os cards iniciais consolidam compromissos futuros e exposicao atual dos parcelamentos.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "installments_filters",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-filters",
    title: "Filtros de parcelamentos",
    description: "Ajuste período, conta, categoria e status para focar apenas nos parcelamentos relevantes.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "installments_insights",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-insights",
    title: "Insights e projecoes",
    description: "Estas seções ajudam a antecipar vencimentos, pressão futura e comportamento das compras parceladas.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "installments_table",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-table",
    title: "Tabela de parcelamentos",
    description: "Aqui você revisa cada parcela planejada e exporta os dados quando necessário.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "housing_filters",
    route: appRoutes.expenseManagementHousing,
    target: "housing-filters",
    title: "Filtros de habitação",
    description: "Use o topo da tela para recortar despesas da casa por período, conta, tipo e busca.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "housing_summary",
    route: appRoutes.expenseManagementHousing,
    target: "housing-summary",
    title: "Resumo da habitação",
    description: "Os cards resumem compromisso do período, séries ativas, média por vencimento e próximo compromisso.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "housing_trend",
    route: appRoutes.expenseManagementHousing,
    target: "housing-trend",
    title: "Evolução e distribuição",
    description: "Este bloco mostra a tendência das despesas e como os tipos de custo se distribuem.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "housing_table",
    route: appRoutes.expenseManagementHousing,
    target: "housing-table",
    title: "Tabela de despesas recorrentes",
    description: "Aqui você gerencia as séries de habitação e revisa as cobranças previstas.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "expense_metrics_filters",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-filters",
    title: "Filtros das métricas",
    description: "Defina o recorte de período, conta e tipo antes de comparar tendências e concentrações.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "expense_metrics_summary",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-summary",
    title: "Resumo operacional",
    description: "Os cards sintetizam despesas, saldo, ticket médio e dias com movimentação no recorte.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "expense_metrics_trend",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-trend",
    title: "Tendencia e categorias",
    description: "Este bloco cruza tendência temporal com concentração por categoria para destacar pressão de gastos.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "expense_metrics_ranking",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-ranking",
    title: "Rankings e leituras rápidas",
    description: "Aqui você entende quais contas e categorias mais pressionam seu resultado.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "insights_summary",
    route: appRoutes.insights,
    target: "insights-summary",
    title: "Resumo dos insights",
    description: "Os cards superiores mostram volume de insights e a categoria que mais pesa no período.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "insights_recommendations",
    route: appRoutes.insights,
    target: "insights-recommendations",
    title: "Insights acionaveis",
    description: "Este painel traz leituras automáticas e recomendações práticas para agir no produto.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "insights_spending",
    route: appRoutes.insights,
    target: "insights-spending",
    title: "Gasto por categoria",
    description: "Ao lado, você enxerga o gráfico e uma leitura rápida para contextualizar os insights.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "notifications_filters",
    route: appRoutes.notifications,
    target: "notifications-filters",
    title: "Filtros de notificações",
    description: "Ajuste status, origem e período para revisar somente os alertas importantes agora.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "notifications_inbox",
    route: appRoutes.notifications,
    target: "notifications-inbox",
    title: "Caixa de entrada",
    description: "Aqui ficam os alertas recebidos, com destaque para leitura rápida e status.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "notifications_details",
    route: appRoutes.notifications,
    target: "notifications-details",
    title: "Detalhes da notificação",
    description: "Ao selecionar um item, este painel mostra o contexto completo e as ações disponíveis.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "notifications_form",
    route: appRoutes.notifications,
    target: "notifications-form",
    title: "Novo lembrete",
    description: "Use este formulário para criar lembretes pessoais direto dentro da caixa de notificações.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "chat_conversation",
    route: appRoutes.chat,
    target: "chat-conversation",
    title: "Conversa com a IA",
    description: "Este painel principal concentra as perguntas e respostas sobre seus dados financeiros.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "chat_suggestions",
    route: appRoutes.chat,
    target: "chat-suggestions",
    title: "Atalhos do chat",
    description: "Use estes atalhos para criar, buscar e organizar conversas financeiras.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "profile_identity",
    route: appRoutes.profile,
    target: "profile-identity",
    title: "Identidade da conta",
    description: "Esta seção resume nome, e-mail, status e plano atual do usuário.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "profile_account",
    route: appRoutes.profile,
    target: "profile-account",
    title: "Conta e tour",
    description: "Aqui você acompanha o progresso do tour, status do plano e sinais principais da conta.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "profile_shortcuts",
    route: appRoutes.profile,
    target: "profile-shortcuts",
    title: "Atalhos",
    description: "Este painel acelera tarefas frequentes, incluindo reiniciar o tour manualmente.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "settings_account",
    route: appRoutes.settings,
    target: "settings-account",
    title: "Conta",
    description: "Comece pelas configurações principais da conta: nome, e-mail e verificação.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "settings_security",
    route: appRoutes.settings,
    target: "settings-security",
    title: "Seguranca",
    description: "Esta seção concentra troca de senha, verificação e ações sensíveis da sessão.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "settings_contact",
    route: appRoutes.settings,
    target: "settings-contact",
    title: "Perfil e contato",
    description: "Aqui ficam telefone e endereço para manter o cadastro completo e pronto para futuras integrações.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "settings_preferences",
    route: appRoutes.settings,
    target: "settings-preferences",
    title: "Preferencias",
    description: "Use esta área para ajustar comportamento local do app e notificações do dispositivo.",
    placement: "top",
    autoScroll: true,
  },
];
