export const appRoutes = {
  dashboard: "/",
  loading: "/loading",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  installments: "/installments",
  expenseManagement: "/gestao-de-gastos",
  transactions: "/gestao-de-gastos/transactions",
  expenseManagementInstallments: "/gestao-de-gastos/parcelamentos",
  expenseManagementFinancing: "/gestao-de-gastos/financiamentos",
  expenseManagementHousing: "/gestao-de-gastos/habitacao",
  expenseManagementMetrics: "/gestao-de-gastos/metricas",
  chat: "/chat",
  insights: "/insights",
  accounts: "/accounts",
  profile: "/profile",
  settings: "/settings",
} as const;
