export const appRoutes = {
  dashboard: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  onboarding: "/primeiros-passos",
  installments: "/installments",
  expenseManagement: "/gestao-de-gastos",
  transactions: "/gestao-de-gastos/transactions",
  expenseManagementInstallments: "/gestao-de-gastos/parcelamentos",
  expenseManagementFinancing: "/gestao-de-gastos/financiamentos",
  expenseManagementHousing: "/gestao-de-gastos/habitacao",
  expenseManagementMetrics: "/gestao-de-gastos/metricas",
  chat: "/chat",
  insights: "/insights",
  accounts: "/accounts",
  admin: "/admin",
  adminOverview: "/admin/overview",
  adminUsers: "/admin/users",
  adminFinancialMetrics: "/admin/financial-metrics",
  adminSubscriptions: "/admin/subscriptions",
  adminActivity: "/admin/activity",
  profile: "/profile",
  settings: "/settings",
} as const;
