export const appRoutes = {
  dashboard: "/",
  transactions: "/transactions",
  installments: "/installments",
  expenseManagement: "/gestao-de-gastos",
  expenseManagementInstallments: "/gestao-de-gastos/parcelamentos",
  expenseManagementFinancing: "/gestao-de-gastos/financiamentos",
  expenseManagementHousing: "/gestao-de-gastos/habitacao",
  expenseManagementMetrics: "/gestao-de-gastos/metricas",
  chat: "/chat",
  insights: "/insights",
  accounts: "/accounts",
  profile: "/profile",
  settings: "/settings",
} as const;
