export const defaultUser = {
  name: "Jo\u00e3o",
};

export const categorySeeds = [
  {
    slug: "supermercado",
    label: "Supermercado",
    icon: "ShoppingCart",
    color: "text-primary",
    groupSlug: "alimentacao",
    groupLabel: "Alimenta\u00e7\u00e3o",
    groupColor: "bg-warning",
    sortOrder: 10,
  },
  {
    slug: "cafe",
    label: "Caf\u00e9 & Lanches",
    icon: "Coffee",
    color: "text-warning",
    groupSlug: "alimentacao",
    groupLabel: "Alimenta\u00e7\u00e3o",
    groupColor: "bg-warning",
    sortOrder: 20,
  },
  {
    slug: "transporte",
    label: "Transporte",
    icon: "Car",
    color: "text-info",
    groupSlug: "transporte",
    groupLabel: "Transporte",
    groupColor: "bg-info",
    sortOrder: 30,
  },
  {
    slug: "energia",
    label: "Energia",
    icon: "Zap",
    color: "text-warning",
    groupSlug: "moradia",
    groupLabel: "Moradia",
    groupColor: "bg-primary",
    sortOrder: 40,
  },
  {
    slug: "moradia",
    label: "Moradia",
    icon: "Home",
    color: "text-primary",
    groupSlug: "moradia",
    groupLabel: "Moradia",
    groupColor: "bg-primary",
    sortOrder: 50,
  },
  {
    slug: "restaurantes",
    label: "Restaurantes",
    icon: "Utensils",
    color: "text-expense",
    groupSlug: "alimentacao",
    groupLabel: "Alimenta\u00e7\u00e3o",
    groupColor: "bg-warning",
    sortOrder: 60,
  },
  {
    slug: "assinaturas",
    label: "Assinaturas",
    icon: "Smartphone",
    color: "text-info",
    groupSlug: "outros",
    groupLabel: "Outros",
    groupColor: "bg-muted-foreground",
    sortOrder: 70,
  },
  {
    slug: "saude",
    label: "Sa\u00fade",
    icon: "Heart",
    color: "text-income",
    groupSlug: "saude",
    groupLabel: "Sa\u00fade",
    groupColor: "bg-income",
    sortOrder: 80,
  },
  {
    slug: "lazer",
    label: "Lazer",
    icon: "Sparkles",
    color: "text-expense",
    groupSlug: "lazer",
    groupLabel: "Lazer",
    groupColor: "bg-expense",
    sortOrder: 90,
  },
  {
    slug: "salario",
    label: "Sal\u00e1rio",
    icon: "Wallet",
    color: "text-income",
    groupSlug: "receitas",
    groupLabel: "Receitas",
    groupColor: "bg-income",
    sortOrder: 100,
  },
  {
    slug: "freelance",
    label: "Freelance",
    icon: "TrendingUp",
    color: "text-income",
    groupSlug: "receitas",
    groupLabel: "Receitas",
    groupColor: "bg-income",
    sortOrder: 110,
  },
];

export const bankSeeds = [
  {
    slug: "nubank",
    name: "Nubank",
    connected: true,
    color: "bg-purple-500",
    currentBalance: 6200,
    sortOrder: 10,
  },
  {
    slug: "itau",
    name: "Ita\u00fa",
    connected: true,
    color: "bg-orange-500",
    currentBalance: 6250,
    sortOrder: 20,
  },
  {
    slug: "bradesco",
    name: "Bradesco",
    connected: false,
    color: "bg-red-500",
    currentBalance: 0,
    sortOrder: 30,
  },
];

export const monthlySummarySeeds = [
  {
    monthStart: "2026-03-01",
    totalBalance: 12158.2,
    totalIncome: 7800,
    totalExpenses: 4990,
  },
  {
    monthStart: "2026-04-01",
    totalBalance: 12450,
    totalIncome: 8200,
    totalExpenses: 4830,
  },
];

export const transactionSeeds = [
  {
    seedKey: "salary-apr",
    categorySlug: "salario",
    bankSlug: "itau",
    description: "Salario",
    amount: 6500,
    occurredOn: "2026-04-05",
  },
  {
    seedKey: "freelance-apr",
    categorySlug: "freelance",
    bankSlug: "nubank",
    description: "Projeto freelance",
    amount: 1700,
    occurredOn: "2026-04-04",
  },
  {
    seedKey: "grocery-pao-acucar",
    categorySlug: "supermercado",
    bankSlug: "nubank",
    description: "Pao de Acucar",
    amount: -342.5,
    occurredOn: "2026-04-06",
  },
  {
    seedKey: "ifood-apr",
    categorySlug: "restaurantes",
    bankSlug: "nubank",
    description: "iFood",
    amount: -67.9,
    occurredOn: "2026-04-06",
  },
  {
    seedKey: "coffee-apr",
    categorySlug: "cafe",
    bankSlug: "nubank",
    description: "Starbucks",
    amount: -28,
    occurredOn: "2026-04-05",
  },
  {
    seedKey: "uber-apr",
    categorySlug: "transporte",
    bankSlug: "nubank",
    description: "Uber",
    amount: -23.5,
    occurredOn: "2026-04-05",
  },
  {
    seedKey: "netflix-apr",
    categorySlug: "assinaturas",
    bankSlug: "nubank",
    description: "Netflix",
    amount: -55.9,
    occurredOn: "2026-04-03",
  },
  {
    seedKey: "energy-apr",
    categorySlug: "energia",
    bankSlug: "itau",
    description: "Conta de Luz",
    amount: -189,
    occurredOn: "2026-04-02",
  },
  {
    seedKey: "pharmacy-apr",
    categorySlug: "saude",
    bankSlug: "nubank",
    description: "Farmacia",
    amount: -45.8,
    occurredOn: "2026-04-01",
  },
  {
    seedKey: "rent-apr",
    categorySlug: "moradia",
    bankSlug: "itau",
    description: "Aluguel",
    amount: -2200,
    occurredOn: "2026-04-01",
  },
  {
    seedKey: "gas-apr",
    categorySlug: "transporte",
    bankSlug: "itau",
    description: "Combustivel",
    amount: -400,
    occurredOn: "2026-04-04",
  },
  {
    seedKey: "market-fair-apr",
    categorySlug: "supermercado",
    bankSlug: "nubank",
    description: "Feira livre",
    amount: -310,
    occurredOn: "2026-04-03",
  },
  {
    seedKey: "restaurant-apr",
    categorySlug: "restaurantes",
    bankSlug: "itau",
    description: "Restaurante da semana",
    amount: -310,
    occurredOn: "2026-04-02",
  },
  {
    seedKey: "internet-apr",
    categorySlug: "moradia",
    bankSlug: "itau",
    description: "Internet residencial",
    amount: -120,
    occurredOn: "2026-04-02",
  },
  {
    seedKey: "cinema-apr",
    categorySlug: "lazer",
    bankSlug: "nubank",
    description: "Cinema",
    amount: -220,
    occurredOn: "2026-04-03",
  },
  {
    seedKey: "uber-friday-apr",
    categorySlug: "transporte",
    bankSlug: "nubank",
    description: "Uber sexta",
    amount: -137.5,
    occurredOn: "2026-04-04",
  },
  {
    seedKey: "gym-apr",
    categorySlug: "saude",
    bankSlug: "itau",
    description: "Academia",
    amount: -89.9,
    occurredOn: "2026-04-02",
  },
  {
    seedKey: "park-apr",
    categorySlug: "lazer",
    bankSlug: "nubank",
    description: "Passeio de fim de semana",
    amount: -290,
    occurredOn: "2026-04-01",
  },
  {
    seedKey: "salary-mar",
    categorySlug: "salario",
    bankSlug: "itau",
    description: "Salario marco",
    amount: 6200,
    occurredOn: "2026-03-05",
  },
  {
    seedKey: "freelance-mar",
    categorySlug: "freelance",
    bankSlug: "nubank",
    description: "Freelance marco",
    amount: 1600,
    occurredOn: "2026-03-11",
  },
  {
    seedKey: "rent-mar",
    categorySlug: "moradia",
    bankSlug: "itau",
    description: "Aluguel marco",
    amount: -2200,
    occurredOn: "2026-03-01",
  },
  {
    seedKey: "expenses-mar-extra",
    categorySlug: "restaurantes",
    bankSlug: "nubank",
    description: "Despesas variaveis marco",
    amount: -2790,
    occurredOn: "2026-03-20",
  },
];

export const insightSeeds = [
  {
    seedKey: "budget-restaurants",
    title: "Gasto acima do orcamento",
    description:
      "Seus gastos com restaurantes ultrapassaram o limite mensal de R$ 500 em 23%.",
    tag: "Atencao",
    tone: "warning",
    sortOrder: 10,
  },
  {
    seedKey: "unused-subscriptions",
    title: "Economia identificada",
    description:
      "Voce pode economizar R$ 180/mes cancelando 2 assinaturas pouco utilizadas.",
    tag: "Oportunidade",
    tone: "success",
    sortOrder: 20,
  },
  {
    seedKey: "emergency-fund",
    title: "Meta de reserva",
    description:
      "Com o ritmo atual, voce atinge sua reserva de emergencia em 4 meses.",
    tag: "Meta",
    tone: "info",
    sortOrder: 30,
  },
  {
    seedKey: "uber-pattern",
    title: "Padrao detectado",
    description:
      "Seus gastos com Uber aumentam 40% nas sextas. Considere alternativas.",
    tag: "Padrao",
    tone: "primary",
    sortOrder: 40,
  },
];

export const chatMessageSeeds = [
  {
    seedKey: "chat-assistant-1",
    role: "assistant",
    content:
      "Ola Jo\u00e3o! \u{1F44B} Analisei suas financas deste mes. Voce gastou 12% a mais em alimentacao comparado ao mes passado. Quer que eu sugira formas de economizar?",
  },
  {
    seedKey: "chat-user-1",
    role: "user",
    content: "Sim, por favor! Quero reduzir meus gastos com delivery.",
  },
  {
    seedKey: "chat-assistant-2",
    role: "assistant",
    content:
      "Otimo! Aqui vao 3 dicas:\n\n1. Cozinhe em lotes no domingo e economize cerca de R$ 400/mes.\n2. Use cupons nos apps de delivery para pedidos essenciais.\n3. Defina um limite semanal de R$ 80 para delivery.\n\nIsso pode gerar uma economia de ate R$ 600/mes. \u{1F4B0}",
  },
];
