CREATE TABLE IF NOT EXISTS housing (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bank_connection_id INTEGER REFERENCES bank_connections(id) ON DELETE SET NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  expense_type TEXT NOT NULL CHECK (
    expense_type IN (
      'rent',
      'home_financing',
      'electricity',
      'water',
      'condo',
      'vehicle_financing',
      'other'
    )
  ),
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  due_day INTEGER NOT NULL CHECK (due_day BETWEEN 1 AND 31),
  start_date DATE NOT NULL,
  installment_count INTEGER CHECK (installment_count IS NULL OR installment_count >= 2),
  notes TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS housing_id INTEGER REFERENCES housing(id) ON DELETE CASCADE;

ALTER TABLE installment_purchases
  ADD COLUMN IF NOT EXISTS housing_id INTEGER REFERENCES housing(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_housing_user_status
ON housing (user_id, status, id DESC);

CREATE INDEX IF NOT EXISTS idx_transactions_housing
ON transactions (housing_id);

CREATE INDEX IF NOT EXISTS idx_installment_purchases_housing
ON installment_purchases (housing_id);
