CREATE TABLE IF NOT EXISTS chat_conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  public_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL DEFAULT 'Novo chat',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DELETE FROM chat_messages;

ALTER TABLE chat_messages
ADD COLUMN IF NOT EXISTS chat_id INTEGER REFERENCES chat_conversations(id) ON DELETE CASCADE;

ALTER TABLE chat_messages
ALTER COLUMN chat_id SET NOT NULL;

DROP INDEX IF EXISTS idx_chat_messages_user_created;

CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_updated
ON chat_conversations (user_id, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_chat_messages_chat_created
ON chat_messages (chat_id, created_at ASC, id ASC);
