CREATE TABLE IF NOT EXISTS investments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bank_connection_id INTEGER REFERENCES bank_connections(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  contribution_mode TEXT NOT NULL CHECK (contribution_mode IN ('fixed_amount', 'income_percentage')),
  fixed_amount NUMERIC(12, 2),
  income_percentage NUMERIC(6, 2),
  current_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  target_amount NUMERIC(12, 2),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'archived')),
  color TEXT,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (btrim(name) <> ''),
  CHECK (
    current_amount >= 0
    AND (fixed_amount IS NULL OR fixed_amount >= 0)
    AND (target_amount IS NULL OR target_amount >= 0)
    AND (income_percentage IS NULL OR (income_percentage >= 0 AND income_percentage <= 100))
  ),
  CHECK (
    (contribution_mode = 'fixed_amount' AND fixed_amount IS NOT NULL AND income_percentage IS NULL)
    OR (contribution_mode = 'income_percentage' AND income_percentage IS NOT NULL AND fixed_amount IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_investments_user_updated
ON investments (user_id, updated_at DESC, id DESC);

ALTER TABLE plans
ADD COLUMN IF NOT EXISTS goal_target_model TEXT NOT NULL DEFAULT 'category'
CHECK (goal_target_model IN ('category', 'investment_box'));

ALTER TABLE plans
ADD COLUMN IF NOT EXISTS goal_investment_id INTEGER REFERENCES investments(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_plans_goal_investment_id
ON plans (goal_investment_id)
WHERE goal_investment_id IS NOT NULL;
