CREATE TABLE IF NOT EXISTS invoice_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bank_connection_id INTEGER NOT NULL REFERENCES bank_connections(id) ON DELETE CASCADE,
  invoice_period_end DATE NOT NULL,
  paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, bank_connection_id, invoice_period_end)
);

CREATE INDEX IF NOT EXISTS idx_invoice_payments_user
  ON invoice_payments (user_id, bank_connection_id, invoice_period_end DESC);
